const MAX_ACTIVITY = 10;
const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 600;
const ACTIVITY_BAR_HEIGHT = 2;
const GRID_X = 20;
const GRID_Y = 20;
const MAX_PLAYER_ACTION_QUEUE_LENGTH = 2;

const SENSE_SIGHT = 1;
const SENSE_TOUCH = 2;
const SENSE_SMELL = 3;
const SENSE_TASTE = 4;
const SENSE_SOUND = 5;
// const SENSE_MAGNET = 6;
// const SENSE_ELECTRIC = 7;
// const SENSE_GRAVITY = 8;

const DEFAULT_SMELL_DISPERSAL = 0.005;
const MAX_SMELL = 5;
